INSERT INTO department (department_name)
VALUES  ("Executive"),
        ("Administrative"),
        ("Operations"),
        ("Financial"),
        ("Marketing"),
        ("Manufacturing"),
        ("Logistics"),
        ("Sponsorship");

INSERT INTO role (title, salary, department_id)
VALUES  ("Chief Executive Officer", 175000, 101),
        ("President", 165000, 101),
        ("Chief Operations Officer", 155000, 104),
        ("Chief Financial Officer", 160000, 107),
        ("Chief Marketing Officer", 135000, 112),
        ("Senior Technical Manager", 95000, 113),
        ("Vice President", 87500, 101),
        ("Executive Assistant", 60000, 101),
        ("Administrative Assistant", 50000, 101),
        ("Marketing Strategist", 55000, 112),
        ("Senior Technician", 64500, 113),
        ("Technician", 57500, 113),
        ("Accountant", 62500, 107),
        ("Junior Accountant", 48000, 107),
        ("Systems Engineer", 75000, 113),
        ("Operations Representative", 42000, 104),
        ("CSR", 35000, 104);

INSERT INTO employee (first_name, last_name)
VALUES  ("Shane", "Van Gisbergen"),
        ("Craig", "Lowndes"),
        ("Jamie", "Whincup"),
        ("Andrew", "Edwards"),
        ("Mark", "Skaife"),
        ("Neil", "Crompton"),
        ("Riana", "Crehan"),
        ("Will", "Davison"),
        ("Jess", "Yates"),
        ("Cam", "Waters"),
        ("Chaz", "Mostert"),
        ("Brock", "Feeney"),
        ("Daffid", "Reynolds"),
        ("Brodie", "Kostecki"),
        ("Mark", "Larkham"),
        ("Garth", "Tander"),
        ("Carlos", "Sainz"),
        ("Charles", "Leclerc"),
        ("Max", "Verstappen"),
        ("Lewis", "Hamilton"),
        ("Sergio", "Perez"),
        ("Daniel", "Ricciardo"),
        ("Christian", "Horner"),
        ("Toto", "Wolff");